# === IMPORTANT: CENTRALLY MAINTAINED FILE ===
# This file was automatically added via the scripts at the maintenance repository.
# Please do not change it. Rather, update the blueprint in the maintenance repository and propagate
# the changes from there.
# IF YOU REALLY WANT TO MAKE REPOSITORY SPECIFIC CHANGES TO THIS FILE, PLEASE REMOVE THIS NOTICE!
# Tag @klieret for any questions.
# ======

# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks a lot for opening your first issue here!
  Should I not get back to you within a few days, feel free to mention me
  with `@klieret`.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks a lot for opening your first pull request here!
  Should I not get back to you within a few days, feel free to mention me
  with `@klieret`.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
# firstPRMergeComment: >
#  Congrats on merging your first pull request!

# It is recommended to include as many gifs and emojis as possible!
