repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: '.*\.ipynb'
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--profile",
            "black",
            "-a",
            "from __future__ import annotations",
            "--append-only",
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        exclude: "docs/.*"
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: "v2.5.0"
    hooks:
      - id: setup-cfg-fmt
        args: [--include-version-classifiers, --max-py-version=3.10]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

ci:
  autoupdate_schedule: monthly
